ENTITY count_0a5 IS
PORT(IN_CLK, RESET: IN BIT;
SAIDA: OUT INTEGER RANGE 0 TO 5;
COUT: OUT BIT);
END count_0a5;

ARCHITECTURE one OF count_0a5 IS
SIGNAL X: BIT;
SIGNAL Y: INTEGER RANGE 0 TO 5:=0;
BEGIN
PROCESS(IN_CLK)
BEGIN
IF RESET = '0' THEN
	Y <= 0;
	X <= '0';
ELSIF (IN_CLK 'EVENT) AND (IN_CLK = '1') THEN
	IF Y = 5 THEN
	Y <= 0;
	X <= '1';
	ELSE
	Y <= Y + 1;
	X <= '0';
	END IF;
END IF;
END PROCESS;
SAIDA <= Y;
COUT <= X;
END one;

