ENTITY Cronometro IS
PORT(CLK: IN BIT;
DISPLAY_0: OUT BIT_VECTOR( 6 DOWNTO 0);
DISPLAY_1: OUT BIT_VECTOR( 6 DOWNTO 0);
DISPLAY_2: OUT BIT_VECTOR( 6 DOWNTO 0);
<<<<<<< HEAD
DISPLAY_3: OUT BIT_VECTOR( 6 DOWNTO 0));
END Cronometro;

ARCHITECTURE one OF Cronometro IS
SIGNAL AUX: BIT;
SIGNAL AUX_1: INTEGER RANGE 0 TO 9;
SIGNAL AUX_2: BIT;
SIGNAL AUX_3: INTEGER RANGE 0 TO 5;
SIGNAL AUX_4: BIT;
SIGNAL AUX_5: INTEGER RANGE 0 TO 9;
SIGNAL AUX_6: BIT;
SIGNAL AUX_7: INTEGER RANGE 0 TO 5;



=======
DISPLAY_3: OUT BIT_VECTOR( 6 DOWNTO 0);
DISPLAY_4: OUT BIT_VECTOR( 6 DOWNTO 0);
DISPLAY_5: OUT BIT_VECTOR( 6 DOWNTO 0));
END Cronometro;

ARCHITECTURE one OF Cronometro IS
SIGNAL AUX_CLK: BIT;
SIGNAL AUX_USDEC: INTEGER RANGE 0 TO 9;
SIGNAL AUX_USCOUT: BIT;
SIGNAL AUX_DSDEC: INTEGER RANGE 0 TO 9;
SIGNAL AUX_DSCOUT: BIT;
SIGNAL AUX_UMDEC: INTEGER RANGE 0 TO 9;
SIGNAL AUX_UMCOUT: BIT;
SIGNAL AUX_DMDEC: INTEGER RANGE 0 TO 9;
SIGNAL AUX_DMCOUT: BIT;
SIGNAL AUX_UHDEC: INTEGER RANGE 0 TO 9;
SIGNAL AUX_UHCOUT: BIT;
SIGNAL AUX_DHDEC: INTEGER RANGE 0 TO 9;
SIGNAL AUX_RUH: BIT;
SIGNAL AUX_RDH: BIT; 



COMPONENT VERIFICADOR IS
PORT(UHCONT: IN INTEGER RANGE 0 TO 2;
DHCONT: IN INTEGER RANGE 0 TO 9;
RESUH, RESDH: OUT BIT);
END COMPONENT;

>>>>>>> 8be6b77 (VHDL Relogio)
COMPONENT DIV_CLK IS
PORT(IN_CLK: IN BIT;
OUT_CLK: OUT BIT);
END COMPONENT;

COMPONENT COUNT_9 IS
PORT(IN_CLK, RESET: IN BIT;
SAIDA: OUT INTEGER RANGE 0 TO 9;
COUT: OUT BIT);
END COMPONENT;

COMPONENT COUNT_5 IS
PORT(IN_CLK, RESET: IN BIT;
SAIDA: OUT INTEGER RANGE 0 TO 5;
COUT: OUT BIT);
END COMPONENT;


COMPONENT COUNT_2 IS
PORT(IN_CLK, RESET: IN BIT;
<<<<<<< HEAD
SAIDA: OUT INTEGER RANGE 0 TO 9;
=======
SAIDA: OUT INTEGER RANGE 0 TO 2;
>>>>>>> 8be6b77 (VHDL Relogio)
COUT: OUT BIT);
END COMPONENT;


COMPONENT DECODIFICADOR_9 IS
PORT(IN_DECK: IN INTEGER RANGE 0 TO 9;
DISPLAY: OUT BIT_VECTOR(6 DOWNTO 0));
END COMPONENT;

<<<<<<< HEAD
COMPONENT DECODIFICADOR_5 IS
PORT(IN_DECK: IN INTEGER RANGE 0 TO 5;
DISPLAY: OUT BIT_VECTOR(6 DOWNTO 0));
END COMPONENT;

BEGIN

CHIP1: DIV_CLK PORT MAP(IN_CLK => CLK, OUT_CLK => AUX);
CHIP2: COUNT_9 PORT MAP(IN_CLK => AUX, RESET => '0', SAIDA => AUX_1, COUT => AUX_2);
CHIP3: DECODIFICADOR_9 PORT MAP(DISPLAY => DISPLAY_0, IN_DECK => AUX_1);

CHIP4: COUNT_5 PORT MAP (IN_CLK => AUX_2, RESET => '0', SAIDA => AUX_3, COUT => AUX_4);
CHIP5: DECODIFICADOR_5 PORT MAP(DISPLAY => DISPLAY_1, IN_DECK => AUX_3);

CHIP6: COUNT_9 PORT MAP (IN_CLK => AUX_4, RESET => '0', SAIDA => AUX_5, COUT => AUX_6);
CHIP7: DECODIFICADOR_9 PORT MAP(DISPLAY => DISPLAY_2, IN_DECK => AUX_5);

CHIP8: COUNT_5 PORT MAP (IN_CLK => AUX_6, RESET => '0', SAIDA => AUX_7);
CHIP9: DECODIFICADOR_5 PORT MAP(DISPLAY => DISPLAY_3, IN_DECK => AUX_7);

END one;

=======

BEGIN

CHIP1: DIV_CLK PORT MAP(IN_CLK => CLK, OUT_CLK => AUX_CLK);

CHIP2: COUNT_9 PORT MAP(IN_CLK => AUX_CLK, RESET => '0', SAIDA => AUX_USDEC, COUT => AUX_USCOUT);
CHIP3: DECODIFICADOR_9 PORT MAP(DISPLAY => DISPLAY_0, IN_DECK => AUX_USDEC);

CHIP4: COUNT_5 PORT MAP (IN_CLK => AUX_USCOUT, RESET => '0', SAIDA => AUX_DSDEC, COUT => AUX_DSCOUT);
CHIP5: DECODIFICADOR_9 PORT MAP(DISPLAY => DISPLAY_1, IN_DECK => AUX_DSDEC);

CHIP6: COUNT_9 PORT MAP (IN_CLK => AUX_DSCOUT, RESET => '0', SAIDA => AUX_UMDEC, COUT => AUX_UMCOUT);
CHIP7: DECODIFICADOR_9 PORT MAP(DISPLAY => DISPLAY_2, IN_DECK => AUX_UMDEC);

CHIP8: COUNT_5 PORT MAP (IN_CLK => AUX_UMCOUT, RESET => '0', SAIDA => AUX_DMDEC, COUT => AUX_DMCOUT);
CHIP9: DECODIFICADOR_9 PORT MAP(DISPLAY => DISPLAY_3, IN_DECK => AUX_DMDEC);

CHIP10: COUNT_9 PORT MAP (IN_CLK => AUX_DMCOUT, RESET => AUX_RUH, SAIDA => AUX_UHDEC, COUT => AUX_UHCOUT);
CHIP11: DECODIFICADOR_9 PORT MAP(DISPLAY => DISPLAY_4, IN_DECK => AUX_UHDEC);

CHIP12: COUNT_2 PORT MAP (IN_CLK => AUX_UHCOUT, RESET => AUX_RDH, SAIDA => AUX_DHDEC);
CHIP13: DECODIFICADOR_9 PORT MAP(DISPLAY => DISPLAY_5, IN_DECK => AUX_DHDEC);

CHIP14: VERIFICADOR PORT MAP(UHCONT => AUX_UHDEC, DHCONT => AUX_DHDEC, RESUH => AUX_RUH, RESDH => AUX_RDH);


END one;

ENTITY VERIFICADOR IS
PORT(UHCONT: IN INTEGER RANGE 0 TO 2;
DHCONT: IN INTEGER RANGE 0 TO 9;
RESUH, RESDH: OUT BIT);
END VERIFICADOR;

ARCHITECTURE one OF VERIFICADOR IS
SIGNAL U: BIT;
SIGNAL D: BIT;
BEGIN
PROCESS (UHCONT, DHCONT)
BEGIN
IF (DHCONT = 2) AND (UHCONT = 3) THEN
	U <= '1';
	D <= '1';
	ELSE 
	U <= '0';
	D <= '0';
END IF;
END PROCESS;
RESUH <= U;
RESDH <= D;
END one;


>>>>>>> 8be6b77 (VHDL Relogio)
ENTITY DIV_CLK IS
PORT(IN_CLK: IN BIT;
OUT_CLK: OUT BIT);
END DIV_CLK;

ARCHITECTURE one OF DIV_CLK IS
SIGNAL X: BIT;
SIGNAL Y: INTEGER RANGE 0 TO 4999999:=0;
BEGIN
PROCESS(IN_CLK)
BEGIN
IF (IN_CLK 'EVENT) AND (IN_CLK = '1') THEN
<<<<<<< HEAD
	IF Y = 4999999 THEN
=======
	IF Y = 499999 THEN
>>>>>>> 8be6b77 (VHDL Relogio)
	Y <= 0;
	X <= NOT X;
	ELSE
	Y <= Y + 1;
	END IF;
END IF;
END PROCESS;
OUT_CLK <= X;
END one;


ENTITY COUNT_9 IS
PORT(IN_CLK, RESET: IN BIT;
SAIDA: OUT INTEGER RANGE 0 TO 9;
COUT: OUT BIT);
END COUNT_9;

ARCHITECTURE one OF COUNT_9 IS
SIGNAL X: BIT;
SIGNAL Y: INTEGER RANGE 0 TO 9;
BEGIN
PROCESS(IN_CLK)
BEGIN
IF RESET = '1' THEN
	Y <= 0;
	X <= '0';
ELSIF (IN_CLK 'EVENT) AND (IN_CLK = '1') THEN
	IF Y = 9 THEN
	Y <= 0;
	X <= '1';
	ELSE
	Y <= Y + 1;
	X <= '0';
	END IF;
END IF;
END PROCESS;
SAIDA <= Y;
COUT <= X;
END one;

ENTITY COUNT_5 IS
PORT(IN_CLK, RESET: IN BIT;
SAIDA: OUT INTEGER RANGE 0 TO 5;
COUT: OUT BIT);
END COUNT_5;

ARCHITECTURE one OF COUNT_5 IS
SIGNAL X: BIT;
SIGNAL Y: INTEGER RANGE 0 TO 5;
BEGIN
PROCESS(IN_CLK)
BEGIN
IF RESET = '1' THEN
	Y <= 0;
	X <= '0';
ELSIF (IN_CLK 'EVENT) AND (IN_CLK = '1') THEN
	IF Y = 5 THEN
	Y <= 0;
	X <= '1';
	ELSE
	Y <= Y + 1;
	X <= '0';
	END IF;
END IF;
END PROCESS;
SAIDA <= Y;
COUT <= X;
END one;

ENTITY COUNT_2 IS
PORT(IN_CLK, RESET: IN BIT;
SAIDA: OUT INTEGER RANGE 0 TO 2;
COUT: OUT BIT);
END COUNT_2;

ARCHITECTURE one OF COUNT_2 IS
SIGNAL X: BIT;
SIGNAL Y: INTEGER RANGE 0 TO 2;
BEGIN
PROCESS(IN_CLK)
BEGIN
IF RESET = '1' THEN
	Y <= 0;
	X <= '0';
ELSIF (IN_CLK 'EVENT) AND (IN_CLK = '1') THEN
	IF Y = 2 THEN
	Y <= 0;
	X <= '1';
	ELSE
	Y <= Y + 1;
	X <= '0';
	END IF;
END IF;
END PROCESS;
SAIDA <= Y;
COUT <= X;
END one;


ENTITY DECODIFICADOR_9 IS
PORT(IN_DECK: IN INTEGER RANGE 0 TO 9;
DISPLAY: OUT BIT_VECTOR(6 DOWNTO 0));
END DECODIFICADOR_9;

ARCHITECTURE one OF DECODIFICADOR_9 IS
BEGIN

WITH IN_DECK SELECT
	DISPLAY <= "0000001" WHEN 0,
					"1001111" WHEN 1,
					"0010010" WHEN 2,
					"0000110" WHEN 3,
					"1001100" WHEN 4,
					"0100100" WHEN 5,
					"0100000" WHEN 6,
					"0001111" WHEN 7,
					"0000000" WHEN 8,
					"0000100" WHEN 9,
					"1111111" WHEN OTHERS;
END one;

<<<<<<< HEAD
ENTITY DECODIFICADOR_5 IS
PORT(IN_DECK: IN INTEGER RANGE 0 TO 5;
DISPLAY: OUT BIT_VECTOR(6 DOWNTO 0));
END DECODIFICADOR_5;

ARCHITECTURE one OF DECODIFICADOR_5 IS
BEGIN

WITH IN_DECK SELECT
	DISPLAY <= "0000001" WHEN 0,
					"1001111" WHEN 1,
					"0010010" WHEN 2,
					"0000110" WHEN 3,
					"1001100" WHEN 4,
					"0100100" WHEN 5,
					"1111111" WHEN OTHERS;
END one;
=======
END one;

>>>>>>> 8be6b77 (VHDL Relogio)
