ENTITY Cronometro IS
PORT(CLK: IN BIT;
DISPLAY_0: OUT BIT_VECTOR( 6 DOWNTO 0);
DISPLAY_1: OUT BIT_VECTOR( 6 DOWNTO 0);
DISPLAY_2: OUT BIT_VECTOR( 6 DOWNTO 0);
DISPLAY_3: OUT BIT_VECTOR( 6 DOWNTO 0));
END Cronometro;

ARCHITECTURE one OF Cronometro IS
SIGNAL AUX: BIT;
SIGNAL AUX_1: INTEGER RANGE 0 TO 9;
SIGNAL AUX_2: BIT;
SIGNAL AUX_3: INTEGER RANGE 0 TO 5;
SIGNAL AUX_4: BIT;
SIGNAL AUX_5: INTEGER RANGE 0 TO 9;
SIGNAL AUX_6: BIT;
SIGNAL AUX_7: INTEGER RANGE 0 TO 5;



COMPONENT DIV_CLK IS
PORT(IN_CLK: IN BIT;
OUT_CLK: OUT BIT);
END COMPONENT;

COMPONENT COUNT_9 IS
PORT(IN_CLK, RESET: IN BIT;
SAIDA: OUT INTEGER RANGE 0 TO 9;
COUT: OUT BIT);
END COMPONENT;

COMPONENT COUNT_5 IS
PORT(IN_CLK, RESET: IN BIT;
SAIDA: OUT INTEGER RANGE 0 TO 5;
COUT: OUT BIT);
END COMPONENT;


COMPONENT COUNT_2 IS
PORT(IN_CLK, RESET: IN BIT;
SAIDA: OUT INTEGER RANGE 0 TO 9;
COUT: OUT BIT);
END COMPONENT;


COMPONENT DECODIFICADOR_9 IS
PORT(IN_DECK: IN INTEGER RANGE 0 TO 9;
DISPLAY: OUT BIT_VECTOR(6 DOWNTO 0));
END COMPONENT;

COMPONENT DECODIFICADOR_5 IS
PORT(IN_DECK: IN INTEGER RANGE 0 TO 5;
DISPLAY: OUT BIT_VECTOR(6 DOWNTO 0));
END COMPONENT;

BEGIN

CHIP1: DIV_CLK PORT MAP(IN_CLK => CLK, OUT_CLK => AUX);
CHIP2: COUNT_9 PORT MAP(IN_CLK => AUX, RESET => '0', SAIDA => AUX_1, COUT => AUX_2);
CHIP3: DECODIFICADOR_9 PORT MAP(DISPLAY => DISPLAY_0, IN_DECK => AUX_1);

CHIP4: COUNT_5 PORT MAP (IN_CLK => AUX_2, RESET => '0', SAIDA => AUX_3, COUT => AUX_4);
CHIP5: DECODIFICADOR_5 PORT MAP(DISPLAY => DISPLAY_1, IN_DECK => AUX_3);

CHIP6: COUNT_9 PORT MAP (IN_CLK => AUX_4, RESET => '0', SAIDA => AUX_5, COUT => AUX_6);
CHIP7: DECODIFICADOR_9 PORT MAP(DISPLAY => DISPLAY_2, IN_DECK => AUX_5);

CHIP8: COUNT_5 PORT MAP (IN_CLK => AUX_6, RESET => '0', SAIDA => AUX_7);
CHIP9: DECODIFICADOR_5 PORT MAP(DISPLAY => DISPLAY_3, IN_DECK => AUX_7);

END one;

ENTITY DIV_CLK IS
PORT(IN_CLK: IN BIT;
OUT_CLK: OUT BIT);
END DIV_CLK;

ARCHITECTURE one OF DIV_CLK IS
SIGNAL X: BIT;
SIGNAL Y: INTEGER RANGE 0 TO 4999999:=0;
BEGIN
PROCESS(IN_CLK)
BEGIN
IF (IN_CLK 'EVENT) AND (IN_CLK = '1') THEN
	IF Y = 4999999 THEN
	Y <= 0;
	X <= NOT X;
	ELSE
	Y <= Y + 1;
	END IF;
END IF;
END PROCESS;
OUT_CLK <= X;
END one;


ENTITY COUNT_9 IS
PORT(IN_CLK, RESET: IN BIT;
SAIDA: OUT INTEGER RANGE 0 TO 9;
COUT: OUT BIT);
END COUNT_9;

ARCHITECTURE one OF COUNT_9 IS
SIGNAL X: BIT;
SIGNAL Y: INTEGER RANGE 0 TO 9;
BEGIN
PROCESS(IN_CLK)
BEGIN
IF RESET = '1' THEN
	Y <= 0;
	X <= '0';
ELSIF (IN_CLK 'EVENT) AND (IN_CLK = '1') THEN
	IF Y = 9 THEN
	Y <= 0;
	X <= '1';
	ELSE
	Y <= Y + 1;
	X <= '0';
	END IF;
END IF;
END PROCESS;
SAIDA <= Y;
COUT <= X;
END one;

ENTITY COUNT_5 IS
PORT(IN_CLK, RESET: IN BIT;
SAIDA: OUT INTEGER RANGE 0 TO 5;
COUT: OUT BIT);
END COUNT_5;

ARCHITECTURE one OF COUNT_5 IS
SIGNAL X: BIT;
SIGNAL Y: INTEGER RANGE 0 TO 5;
BEGIN
PROCESS(IN_CLK)
BEGIN
IF RESET = '1' THEN
	Y <= 0;
	X <= '0';
ELSIF (IN_CLK 'EVENT) AND (IN_CLK = '1') THEN
	IF Y = 5 THEN
	Y <= 0;
	X <= '1';
	ELSE
	Y <= Y + 1;
	X <= '0';
	END IF;
END IF;
END PROCESS;
SAIDA <= Y;
COUT <= X;
END one;

ENTITY COUNT_2 IS
PORT(IN_CLK, RESET: IN BIT;
SAIDA: OUT INTEGER RANGE 0 TO 2;
COUT: OUT BIT);
END COUNT_2;

ARCHITECTURE one OF COUNT_2 IS
SIGNAL X: BIT;
SIGNAL Y: INTEGER RANGE 0 TO 2;
BEGIN
PROCESS(IN_CLK)
BEGIN
IF RESET = '1' THEN
	Y <= 0;
	X <= '0';
ELSIF (IN_CLK 'EVENT) AND (IN_CLK = '1') THEN
	IF Y = 2 THEN
	Y <= 0;
	X <= '1';
	ELSE
	Y <= Y + 1;
	X <= '0';
	END IF;
END IF;
END PROCESS;
SAIDA <= Y;
COUT <= X;
END one;


ENTITY DECODIFICADOR_9 IS
PORT(IN_DECK: IN INTEGER RANGE 0 TO 9;
DISPLAY: OUT BIT_VECTOR(6 DOWNTO 0));
END DECODIFICADOR_9;

ARCHITECTURE one OF DECODIFICADOR_9 IS
BEGIN

WITH IN_DECK SELECT
	DISPLAY <= "0000001" WHEN 0,
					"1001111" WHEN 1,
					"0010010" WHEN 2,
					"0000110" WHEN 3,
					"1001100" WHEN 4,
					"0100100" WHEN 5,
					"0100000" WHEN 6,
					"0001111" WHEN 7,
					"0000000" WHEN 8,
					"0000100" WHEN 9,
					"1111111" WHEN OTHERS;
END one;

ENTITY DECODIFICADOR_5 IS
PORT(IN_DECK: IN INTEGER RANGE 0 TO 5;
DISPLAY: OUT BIT_VECTOR(6 DOWNTO 0));
END DECODIFICADOR_5;

ARCHITECTURE one OF DECODIFICADOR_5 IS
BEGIN

WITH IN_DECK SELECT
	DISPLAY <= "0000001" WHEN 0,
					"1001111" WHEN 1,
					"0010010" WHEN 2,
					"0000110" WHEN 3,
					"1001100" WHEN 4,
					"0100100" WHEN 5,
					"1111111" WHEN OTHERS;
END one;
