ENTITY EDAp1Q2 IS
PORT(P1, P2, I, F: IN BIT;
S: OUT BIT);
END EDAp1Q2;

ARCHITECTURE one OF EDAp1Q2 IS
SIGNAL X: BIT_VECTOR(2 DOWNTO 0);
BEGIN

S <= (P1 AND I) OR (P2 AND I) OR (P1 AND F) OR (P2 AND F) OR ((NOT I) AND F);

END one;